### ISSUE TITLE
Ton Connect 2.0 plan

### ISSUE THREAD

**Issue by oleganza** [tonkeeper/ton-connect#11]
UPDATE: Ton connect 2.0 is moved to a separate github org: https://github.com/ton-connect

### Use-cases to focus on

Primary: mobile dapps serverless or via Telegram bots ([TWA](https://core.telegram.org/bots/webapps)) working together with mobile native wallets.

Secondary: 
* server applications,
* desktop web- or standalone apps with mobile wallets, 
* web dapps running as extensions within the mobile wallet.

Tertiary: web-apps working with a chrome extension, and non-native wallets.

### Architecture

1. Each wallet provides a bridging service for the app to connect with. User selects a wallet explicitly in the "Connect with TON" prompt.
2. SSE and POST requests over the bridge.
3. Sessions can be re-started at whim by the dapp.
4. Single SDK to initiate connections.
5. Separate starting points for connecting a wallet (passing over the unauthenticated wallet address) & signing in.
### Checklist

- [x] Define the JS API for initiating connections and setting up the prompt.
- [x] Define the format for wallets' descriptions with their bridge addresses, icons and names.
- [ ] ~Ton Connect prompt design and layout (buttons, modal window with wallet buttons, pending confirmation window).~ Moved to a separate library; we'll focus on pure API in initial release.
- [x] Message encoding connect requests and responses: connect, sign in, sign tx.
- [ ] ~Define a mechanism for attaching TON.DNS records immutably - as DNS items or via a separate registry.~ Serverless dapps don't have their own backend and do not use DNS authentication.

**Comment by Hiyorimi** [comment]
What's up?

**Comment by Hiyorimi** [comment]
👀

**Comment by oleganza** [comment]
Moved to a separate org: https://github.com/ton-connect

**Comment by Hiyorimi** [comment]
🎉Yay!
